# Generated by Django 2.2 on 2020-08-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cretated',
            new_name='created',
        ),
    ]
