# Generated by Django 2.2 on 2020-09-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20200915_2052'),
        ('blogapp', '0007_auto_20200912_0129'),
    ]

    operations = [
    ]
